= Advent of Code
:toc:

My solutions to the AoC tasks, with focus on exploration and fun.

== 2021

My first AoC. I want to use these fun little riddles to try out programming
languages and maybe tooling around them. Stuff which I collect on my to-do
list, but have missed the opportunity to try them out during the year. I like
how these mini tasks offer a nice way to mess around new things without
commiting to a full side-project.

I started off using https://repl.com[repl.com], but then decided to also create
this repo to gather my notes around the solutions.

=== Day 0.

Trying out https://docs.asciidoctor.org/asciidoctor/latest/[Asciidoctor] as a
Markdown alternative.

=== Day 1. - Depth Scan (Rust)

After hearing so much about rust, it is time to try it out!

* Reading a file : https://doc.rust-lang.org/book/ch12-02-reading-a-file.html
* Iterator : https://doc.rust-lang.org/std/iter/trait.Iterator.html
** `windows()` <3

The syntax sure needs some getting used to. But I am impressed with the
functional toolbox. And this "iter.collect.iter.collect" schema does look
promissing! I started to think, how general this sliding window use-case is,
and how I would implement it in C. Then discovered `windows()` in the docs...
Neat!

The pattern matching and the borrow-checker will need some more learning...

.Building and running the solution
[source,bash]
----
# Sample data-set part-1
cargo run sample.txt a
# Input data-set part-2
cargo run input.txt b
----

=== Day 2. - Keyword navigation (awk)

I've been using awk to print some selected columns from files... But knew it
could do more!

* `-v=0` flag is redundant, because variables are initialized to 0

I think I will use awk more in my day-to-day work. Pretty awesome to have match
based actions!

.Running the solution
[source,bash]
----
./aoc-2021-02.sh sample a
./aoc-2021-02.sh input b
----

=== Day 3. - Conan Pakage Manager, std::fmt

Managing dependencies for C/C++ can be a pain. I heard much about vcpkg and conan,
but never got the time to play around with them.

Also wanted to give a try to C++20's fmt feature. But had to see that GCC doesn't
yet support it.

So, why not try to include libfmt via a package manager and CMake?

On first look vcpkg had a lot less packages than conan, so I went with conan.

Boy, the configuration turned out to be a surprise... Do I write `cf.py` or `conanfile.txt`??
But the addition to CMake was quite nice!

So now I can build the programm with the following dance moves:

[source,bash]
----
# Prev: profile setup...
$ conan install .
# This generates conanbuildinfo.cmake among others
# This on Arch Linux misses binary, because of bleeding edge compiler...
$ conan install --build=fmt .
# Yey! That was easy, and the CLI gave good suggestions!
$ mkdir tmp && cd tmp
$ cmake .. && make -j
$ ./bin/aoc-2021-03 a ../input
----


== 2022

=== Day 1. Calorie Counting

Let's play some more with AWK! This time as a script in its file with shebang.
There is an AWK syntax file for VS: https://github.com/JohnNilsson/awk-sublime

We can call it after downloading the input into `input-a`:
[source,bash]
----
./calories.awk <input-a
----

Part B, was to find the sum of the top 3 calorie packages. I thought about adding
the top 3 extension with variables to AWK... but yuck.

Then C++'s priority queue came to mind, but then why leave the shell?
By stripping down the original solution and using, `sort` and `head` as well:

[source,bash]
----
./calories-parsums.awk <input-a | sort -nr | head -n 3 | awk '{total += $1}; END {print total}'
----

=== Day 2. Rock Paper Siccors

Kept going with AWK... Because of the rotating value/enumeration it was quite a meditative
typing aout of the 9 awk lines which create the solution as kind of a look-up matrix.

=== Day 3. Rucksack

Let's take this as a challange! Even thought not line oriented in itself anymore,
so how would I solve it in the terminal?

Wow, I leant about `paste` which is a file-based zip :)

`grep -o .` nicely splits up the string into new-line separated letters.

A look-up table in awk is fancy for doing the prio enumeration

[source,bash]
----
# split the input lines
./t1.awk <input >first 2>second
# Find common letter in first and second part
./t1.sh >items
# numeration and sum
./t1-translate.awk <items
----

I made a mistake first in `t1.sh` where grep would return multiple matches,
so `item` ended up having more entries than input lines...
Splitting the input into lines and using `-m 1` flag remedy this.

Still the core `t1.sh` part has a miserable complexity.
I will do a nicer solution later in some other programming language.
Still this was a nice challange for the terminal.
