= Advent of Code
:toc:

My solutions to the AoC tasks, with focus on exploration and fun.

== 2021

My first AoC. I want to use these fun little riddles to try out programming
languages and maybe tooling around them. Stuff which I collect on my to-do
list, but have missed the opportunity to try them out during the year. I like
how these mini tasks offer a nice way to mess around new things without
commiting to a full side-project.

I started off using https://repl.com[repl.com], but then decided to also create
this repo to gather my notes around the solutions.

=== Day 0.

Trying out https://docs.asciidoctor.org/asciidoctor/latest/[Asciidoctor] as a
Markdown alternative.

=== Day 1. - Depth Scan (Rust)

After hearing so much about rust, it is time to try it out!

* Reading a file : https://doc.rust-lang.org/book/ch12-02-reading-a-file.html
* Iterator : https://doc.rust-lang.org/std/iter/trait.Iterator.html
** `windows()` <3

The syntax sure needs some getting used to. But I am impressed with the
functional toolbox. And this "iter.collect.iter.collect" schema does look
promissing! I started to think, how general this sliding window use-case is,
and how I would implement it in C. Then discovered `windows()` in the docs...
Neat!

The pattern matching and the borrow-checker will need some more learning...

.Building and running the solution
[source,bash]
----
# Sample data-set part-1
cargo run sample.txt a
# Input data-set part-2
cargo run input.txt b
----

=== Day 2. - Keyword navigation (awk)

I've been using awk to print some selected columns from files... But knew it
could do more!

* `-v=0` flag is redundant, because variables are initialized to 0

I think I will use awk more in my day-to-day work. Pretty awesome to have match
based actions!

.Running the solution
[source,bash]
----
./aoc-2021-02.sh sample a
./aoc-2021-02.sh input b
----

=== Day 3. - Conan Pakage Manager, std::fmt

Managing dependencies for C/C++ can be a pain. I heard much about vcpkg and conan,
but never got the time to play around with them.

Also wanted to give a try to C++20's fmt feature. But had to see that GCC doesn't
yet support it.

So, why not try to include libfmt via a package manager and CMake?

On first look vcpkg had a lot less packages than conan, so I went with conan.

Boy, the configuration turned out to be a surprise... Do I write `cf.py` or `conanfile.txt`??
But the addition to CMake was quite nice!

So now I can build the programm with the following dance moves:

[source,bash]
----
# Prev: profile setup...
$ conan install .
# This generates conanbuildinfo.cmake among others
# This on Arch Linux misses binary, because of bleeding edge compiler...
$ conan install --build=fmt .
# Yey! That was easy, and the CLI gave good suggestions!
$ mkdir tmp && cd tmp
$ cmake .. && make -j
$ ./bin/aoc-2021-03 a ../input
----


== 2022

=== Day 1. Calorie Counting

Let's play some more with AWK! This time as a script in its file with shebang.
There is an AWK syntax file for VS: https://github.com/JohnNilsson/awk-sublime

We can call it after downloading the input into `input-a`:
[source,bash]
----
./calories.awk <input-a
----

Part B, was to find the sum of the top 3 calorie packages. I thought about adding
the top 3 extension with variables to AWK... but yuck.

Then C++'s priority queue came to mind, but then why leave the shell?
By stripping down the original solution and using, `sort` and `head` as well:

[source,bash]
----
./calories-parsums.awk <input-a | sort -nr | head -n 3 | awk '{total += $1}; END {print total}'
----

=== Day 2. Rock Paper Siccors

Kept going with AWK... Because of the rotating value/enumeration it was quite a meditative
typing aout of the 9 awk lines which create the solution as kind of a look-up matrix.

=== Day 3. Rucksack

==== More Shell
Let's take this as a challange! Even thought not line oriented in itself anymore,
so how would I solve it in the terminal?

Wow, I leant about `paste` which is a file-based zip :)

`grep -o .` nicely splits up the string into new-line separated letters.

A look-up table in awk is fancy for doing the prio enumeration

[source,bash]
----
# split the input lines
./t1.awk <input >first 2>second
# Find common letter in first and second part
./t1.sh >items
# numeration and sum
./t1-translate.awk <items
----

I made a mistake first in `t1.sh` where grep would return multiple matches,
so `item` ended up having more entries than input lines...
Splitting the input into lines and using `-m 1` flag remedy this.

Still the core `t1.sh` part has a miserable complexity.
I will do a nicer solution later in some other programming language.
Still this was a nice challange for the terminal.

==== Python makes me happy

First the `Counter` class came into my mind,
but when searched for aa method to calculate
the intersection of Counters,
I came accross the feature of the
`set`, which fantastically supports
intersection via `&`.
This is so intuitive! I used such notation in
school when we studied set theory.
Python feels even more "batteries included"
whe switching directly from the Shell.

Also, this was the first task solved entirely on my phone!
Not a great experiance, but possible. (Pydroid 3)

==== C++ for fun?

I wanted to solve this with bitmaps for fun,
and because the letters (56) fit into a u64.
The "fun" had a hickup when `1 << i` resulted
in huge 0xFFF...000 values.
After annotating the type with `1llu` everything
fell into place and the fun came back.
It would be interesting to benchmark,
consume the whole input at once, create more efficient
mappers etc... but I want to continue with the
other tasks as well.

This I also did on my phone (C4droid).

==== Part 2. Here we chunk again

**Python**
Since during last year's AoC I have found `chunks` in the rust STL, I always
look for this helper in higher level languages. E.g. this already came in handy
when I reviewed some C# code (for me not a well known language).

So I was suprised that I couldn't find something similar in Python's `itertools`.
But when scrolled far enough in the [documentation](https://docs.python.org/3/library/itertools.html#itertools-recipes)
I could find `more-itertools`, which have the comfortable helpers. (Immediate and iterator based both.)

So there are quite a few similar helpers:
- `(i)chunked` list ot iterable
- `sliced` (can tolerate incomplete windows), returns slices (which were new for me)
- `batched` (tolerates incomplete windows) splits with lists
- `grouper` (has more advanced features, e.g. fillvalue), returns tuples

**C++**
I want to have chunks in this language...
As of C++23 it looks like [ranges.chunk](https://en.cppreference.com/w/cpp/ranges/chunk_view)
brings this to the language! Now I just need a compiler which already implemented this.
On Arch GCC 12.2.0 didn't have this yet, but trunk should as of [compiler explorer](https://godbolt.org/z/nMn4jvTP6)

So this was an interesting experience... Ranges totally got me enthusiastic about
this "modern" C++ I have heard but used so much about.
Still it feels like ranges really needs C++23 to shine. E.g. it would make sense
to have accumulate/reduce in the ranges context. But also nice work that the
implementation can always fall back to the iterators, which are used in `<algorithm>`
and `<numeric>`.

https://godbolt.org/z/szEMdzhMG

== 2023

This year I dived into JS/TS with bun. Next to the language and the bun, I was
very impressed with the mobile version of repl.it! It made it possible to try out
bun on the go, and compared to last year's browser experience, the app (with
the integrated keyboard extension line) was a real enabler!

=== Day 1.

I happen to find myself on the front-end after nearly 10 years again
and a lot has changed there. So let's use some of the AoC tasks to
refresh/learn some TS/JS!
E.g. I was used to the "require()" based imports and had to look up
why sometimes I still see that and why not just use imports.
Now I've read up on CJS vs ESM... yup back to JS-land...
Also I wanted to try out bun for a while, so this is also a great
excuse to do so :)

Bun feels really, really fast, and the error descriptions are nearly as good as
the ones I am used to with Python.
But also, e.g. the `file.readLines()` from node is of course not awailable...

[source,bash]
----
bun run main.ts
----

And there is even a nice, built-in watch mode which works for simple files as well!

[source,bash]
----
bun --watch run main.ts
----

At the second part the overlapping case like `eightwo` had me thinking, because I
expected understood the description so that the result should be 88 instead of 82.
But after trying out the result from the "overlapping" solution, I see it wasn't
meant like that :-). Strange, I thought I could solve that with regex as well, but
with look-ahead and look-behind I couldn't get it to work.

=== Day 2.

After setting up Bun and warmin up with JS regex methods, and with the nice
`strtoul` kind of behaviour of `parseInt` this was rather straight forward.

=== Day 3.

I was thinking about whether to look around the numbers or the stars. Looking around
the stars seemed cleverer, but I didn't want to deal with the possible double counting,
and reconstructing numbers on the same line from e.g. a middle digit. So searched around
the numbers.

When looking at the methods of the `Array` class, I was suprised to see `copyWithin`,
but the name is a bit missleading, as it works more like `memmove` than `memcpy`.
So I ended up duplicating the first and last rows with `unshift` and `push`.
`matchAll` with the match meta-info was the main tool then for the solution for part B.

=== Day 4.

Quite straight forward. Now I used JS's `Set` and `Map` for the first time.
Map was a surprise, because of the `{}` Object. But I can see how Map could be useful
for really using only a map, and not be surprised by the prototype methods of Object.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#objects_vs._maps

`.map(Number)` was a nice surprise, I stumbled upon it and cannot understand why I didn't thought about it before.

`for (const [card, wins] of winMap)` was also new. a bit of a mouthful, but ok.

The B part's solution is ugly, would be nice to revisit it for a clean-up.

=== Day 5.

From this day on I started to reuse the same repl.it project, so I don't need to
bootstrap each time from the template.

I started using bun's test runner with a modified `.replit` `run` command:
```
run = bun test ./d5.test.ts
```

This is great, because like this I can just hit the "run/play" button in the app,
and have the tests run. Then only need to modify the test to run when mofing to a new day.

The solution itself wasn't qreat, and part B actually failed to scale with the
brute force solution.

I was thinking about an inverse (from soil to seed) solution, but it didn't click.
So what I did for part B was to use the hunch that the interesting intervals are
between breaks in the functions, and that the function segments are monoton increasing.
So to find minimums, I just needed to look around the breaks. Still, the "around"
was surprising, because without a +-1 around the breaks, the minimum wasn't reached.

Here also some cleanup would be nice, esp. using recursion instead of repetition.

Takeaways:
- Custom sorters
- No built-in binary search???
- `flat()` is pretty useful
- Would be nice to have a debugger in repl.it app. Now `console.log` was my friend.
- First generator functions in JS
