// Done on compiler explorer for GCC trunk: https://godbolt.org/z/szEMdzhMG
#include <algorithm>
#include <iostream>
#include <ranges>
#include <string>
#include <vector>
#include <cctype>
#include <cstdint>
#include <string_view>
#include <numeric>
#include <functional>

// input file as lines
static std::vector<std::string> input{"mjpsHcssDzLTzMsz",
                                      "tFhbtClRVtbhRCGBFntNTrLhqrwqWMDMTWTqMq",
                                      "LltbngLGRSBgSgGRCJdSdQHvdfmQccmjSQ",
                                      "lBslsZDDWdGdGpSMts",
                                      "grQhDvqLQHDNGJJtbRMQQJ",
                                      "HChCTnnLCgCrTZPPFzzVPcVD",
                                      "ShrzjhNGrNqrhWnHHfVHbhnHbbhH",
                                      "RBsvcBcDCdsRTsvgCgcPFRQpVQGQJPVFbnJfbJ",
                                      "DvsTsdlCBsGLrjzmlqqz",
                                      "WJJqZTgCnBLGCZBJCJnTLggTDDSDDMNdDSdbdSSsWDFfMsFf",
                                      "PVjqpVHmPpvmcjhrRprFmQQffbfNbQMMsSMQNQ",
                                      "cwcpRvrVlVgwtBwZqBzZ",
                                      "qfJJmpqpmhsggvvpVPZCrhdFLFzZFDdLLh",
                                      "CtCTBctGcGLSzZddGZSW",
                                      "RlNjBCnjttBHHMMcQHCsRfsbfwgggmmJvmgfpm",
                                      "ZmcgBBZhZMsnqnCPjpHPjLHp",
                                      "dGbNwNtlTMTzGfNvTvdwNGVLPpQHPjLQPCpCjPqjLbpLPR",
                                      "dvDTdfvNBhDZMBDZ",
                                      "cvvRvbqcllbBVlvVVbVVlbVDjRjDjdMsHPZPGdDPGPHrDP",
                                      "FwtpfwJtWwNtTTNnwFCtjDJsQdQPPPPMrjrPJHjH",
                                      "CwFpnppgntShgbsscbms",
                                      "cWMFMQpFNcvNDdBDgdsT",
                                      "MPrrfrCHBBsDZCBJ",
                                      "LmLjMLjjLWpVcRVR",
                                      "ZrRZqlZMqTWrMDqwvnvVtnsvddvVnlVf",
                                      "pQNhhLNNGmLjhhcfvndDpffdfdVf",
                                      "QGjCLCQGmNgPBQDFFgTMJWWwMRTrTZWWBWTr",
                                      "WrZWZPHHWZHprZVmVvqddBttBBhGhtvh",
                                      "gzDlMTJDMfqhBGllhl",
                                      "jJLqMMDDbbqjLpPHcsHLWZspPr",
                                      "bsSVRVGsrDstrrSjcQjcjlPwzjQl",
                                      "gHBggFNTTvTgfqgCFzljWwLWQQQnrwQWnf",
                                      "NvJHgpgHvqBhNBJhHTvpBCJCZmtdpDsGsZdZMZRbVbbMdrZs",
                                      "MPPtPwPnRnMPPnwrtNSGgLSCGGGNSLtSgD",
                                      "hBhWFjfCsTbbbWqFFWBBqBhsWZVGSVglZHLSVDlNWDNHHGgV",
                                      "zsCfTsTCMdmRPwzQ",
                                      "JVQVvvszzvTsVsVJjctppcCtjtPRcTlP",
                                      "MdFgqSddMqMDbtDlNjRDSR",
                                      "qFZWZqwHlZfZvzvZfLZn",
                                      "vpqwQSsHSHDQzDpgzwZlRLRZRRZTnTrrvGhh",
                                      "JBcdmbmFMPgPbgfrZRZnRFFnrnLRln",
                                      "JNdBNgbdJmPMWSSDzwVDtwSWWW",
                                      "BDMcDDppHCStpWcHBDNtzPJjqGlllPMJzPGjwjlq",
                                      "CZdZLmgCdqbPzjblZj",
                                      "vndLfnghRQmVrhdvgBHpSCDWHBBCVHNppD",
                                      "WrhrJJGSWzpTWwts",
                                      "VlLPmqgmRNZRGwsvttjgcwsT",
                                      "PDZmlbdVqLmPlddVNRDmmmbbSFHrCFQCnFBFJHSJGrDQCBrr",
                                      "hvPdpvhHvHvPrNfVhDfjggFfRV",
                                      "zlGwJGslsSDRfjsg",
                                      "MJMWjMJzwqWGzJwMqJBTCmHndPPdCBvmdCpmHn",
                                      "PVWFpQhJhFJpGbRCvRHGCp",
                                      "jgslDjftsqhNglTgllgTqMnlHwCcvwZwRccSRCbGSGbCMHRw",
                                      "TgjhNNnjlTfjTdDqTfhjnmzmWPzWrLdrQBPJFWJWBB",
                                      "qPPRMPlfSzSSSPPnnLnqMlpQQtrrtmWpbFtQrdzrtrWt",
                                      "BBvCcwsVThsBgswDBCFQHQpdmQvtrFpWFvWp",
                                      "gCghTJgVCgDGVMlRGMqZnSWqlM",
                                      "RWbHvrbHBsbWBHJWvJwMtmdZwdtmdvwMZQff",
                                      "DRVjcqhRchhGGllhCgdGQQzfttzGQGwQfg",
                                      "cDRljchpqTcjDFTFVcPcPCWBHpNnJNNSnbWbHHrSpWHr",
                                      "dtHrRrBHrCRhddftjgBrRhgjsbbbMpbSWSTjWcsDTWDbcW",
                                      "GQPFVQVQnJlqVMDcMzpDfzpDVD",
                                      "qZZJFLlLnvFFGPGLPqnJvwQldfgHrBRBmBhgNBRHghNhhwRg",
                                      "rLbrZhPgqZhMdVFSFTSGCqFG",
                                      "zsszfRzjtHtzvRTSDdFFCtdDdtND",
                                      "fcwllfmwzRHlfmmzFvQQLrgLMLBZhJQZPrZhJLhW",
                                      "sllrCfpQQJpMHLgzwDwpNqzzVDpV",
                                      "RZPFZPGcSMFtGPRGMwNDVwdRgzvNwgqNvg",
                                      "hBmbMcBmcThmcGtSFTZfQCJjrHLJfsjhWJssJl",
                                      "DqGCbGfCRhfZCVbbqDJJGJBgRNpNdpBNNgNBBNwHnRgt",
                                      "rcWSsSSPSQtwBwHD",
                                      "MLscLMzvvTvcTLzvWWFDPTTrGqmFGGqCZJGbblbVbVZZVmFJ",
                                      "FprpsLQTrstQHNmVSVml",
                                      "JMggWPggWcRbwgJPCGMcGcfmzHlMNSjfzVNhHfVtzSMz",
                                      "cwnPnBwgnGRgRCgRbWJLpFsLtFBLFrDLFZZDrL",
                                      "lVgjLLLMgFMDCwCFqCRbngsvnGSvnSGndbsfgf",
                                      "WZJcTWcNTmJZphmTJJNQHcdvfdbvnRRGbGthdrbttfSv",
                                      "ZPQTJTpTNPJNQTmJRBZJNBHjwMVwPCMwVlVzjwwzqqjVjL",
                                      "hznNhNQNQFDWVFmDQm",
                                      "SMqZBMMbBvDbHPzzdVPH",
                                      "zzzTBTMLNTgpnTTh",
                                      "NLCdmsdCVLGHCHdQzzmznnFwRjFMDMwpTBjDRpnpTBMJ",
                                      "PrcfcrglcfWbSqgrlqvShrwpJpDBFJHpBWjTDTRTRTTB",
                                      "crSgSHtPttfdLGmtzzZNNV",
                                      "BTlTVqCBqtTcBqVhWlsJjDvsnLsvlvpJPj",
                                      "gMgggGZbSMzNRRRLmZZnQZQPPDvnsnDvJwwQ",
                                      "dMRRmMgbNfRgmfSdGFgNgTBtrhrhqfWtLCCWLTWWHc",
                                      "zcfVrPwnwrPmrvnjdFdBbHFFdd",
                                      "CCqpSSQQpQZLDCSHPpBFvFBjTHRvRR",
                                      "DMLGthLZMLtQGhGNMPqGSDflzfwcVmzJzsfgNVrswcrr",
                                      "hSgvMTQvChSqPvhTrRLlVHJgfgRJlHHHJH",
                                      "jmzsZzZzwmmLGGtwtVJWNNDRDtVcfVRl",
                                      "GnBBLbzzzFszBFpzvSdrQQCTCQbhMvSQ",
                                      "VHpTMrZMMbDbbpTZmQmTnmzhTqjqlWWQ",
                                      "GGvgNsvNCNvvGvlqqdzWZmlsmZqZ",
                                      "wNNNgccNGJSNBSRNBNvNcvJHLDDZMFRMppMLrfHDLbrrHF",
                                      "spssbPMLpPllspGNsNWMrnwddnfcqrnwwwwMwM",
                                      "VmQBFCjzzjmfnwbrngcVrd",
                                      "FQbSFjBvvzsWvWGlvWNl",
                                      "JLFSwfwRLLfGhnQJBQshvn",
                                      "pZgNcpCWpWtcvhjGGjtVvszD",
                                      "CccMcPcgTTCWmcZcWMcmTNZPmHdrqSHFRRrqwrSrRqwrHmsH",
                                      "BPMhflJRhqnPNGjNRNRjgSRm",
                                      "VdVsDswTVZbCwCZBrcDCczTwtjtNNjmjmgpmjpQggpGVSgQm",
                                      "sTbWrsTBbrTPPnqlJnPPhW",
                                      "nvrgjMWBvQWPvQnsZfGcZcRFdGFtdtZB",
                                      "bHVDwmqNNDhHNzqpphLNHVLpSJcdZtfffRZdDgRFGSddcRZt",
                                      "HNLNqNqLNbhqVVbClngjnQWPTWgsCgvT",
                                      "tfstpcScscBTFTpFnsWSmgdzJlgmgBmPPzJmvdPm",
                                      "jnrqrLHRwGrwhdPvvPvhjJmP",
                                      "qqCLRCGrZZqCHRVtVWQptFWppnbcWb",
                                      "wCDJZJgDwHpdqHhdGHBhhH",
                                      "WSPmJMlmbSmztQlQsvPhnhGGdBddBqdGddTbVB",
                                      "WzWQftWMSWtmvmmSWtMQPgggpZwLwZjggJFgrpFCfj",
                                      "MvQBJMBQhjQFNFnjnj",
                                      "dtlZmRtLmjSTSLLtTtNVwWzDRzDVwwWFwnNn",
                                      "dmmLCqTdcLqtLGqjBhpfHqBGpv",
                                      "PBPRhjTPPlLRBvlvfwffqJGfpG",
                                      "rHtMtrszFtSgbFrrggrFgMnwWGzmQqWvGWzGQpJGfNqqNz",
                                      "FggcbSMntVgMdRCwZcjChLCT",
                                      "lCqqBlCwlnDqPZTZZBLNdjJLwttNWjjdzJzc",
                                      "fVfMbvbvmbVsmSsmMVWNtzzcjgLWgjztMMtg",
                                      "VVmFhFRSfbQsvVQmvSfhSsmzHlCZqrrBrDBrHZPRTZnnzB",
                                      "CRrDWmzRRQMmDqrrBgBQmtHljhHwtwlwplcBjHGwwB",
                                      "PWfPSWnvsNZSZdfjHjZtGHjchllltl",
                                      "WVsnbSPTbNdbmqTQmmrmLzTq",
                                      "cGtMBGSJDgtgMBsBMgMvWWSHWjpjzHTWTPpqWzqW",
                                      "mNVQNsdVsdhLmCpTWWjmCjTT",
                                      "NQQwrfbQrNQNbrrdLwfQsZdgFbBBFBgggRGRDMRFFMRDgM",
                                      "lFnqgqWQvHWqgvlVglvqjPjcLdfLfBPLnrbLNLcN",
                                      "hmTmthppsRtpTRRTZMpSbLdNjNcJLcrcBNbJBZZc",
                                      "smmpRsTtpSSsRGhppmmhdCMGWwqFQgWGWWDgWwVFHQqHgg",
                                      "mWFjmcdcFWcSSQjzrpvrwRGvTwQGGG",
                                      "HRJfgMZVhtRlHJHBVJTGvGppbpbvvGTvTtrv",
                                      "glsgVMVqffdnPRDcqLnL",
                                      "MtvLJdmLLTvSSCtSzLSTcDhRjRftQjjssshfQNjPtf",
                                      "nlggrFWzRsfFjVQN",
                                      "WgwwBgbgZBHGBnccTzMCLTZJmLLL",
                                      "sRtHTBBHZtDTtZhdPzWdGcdVFdJmGcnm",
                                      "wpwMLWCgvfNvwvwbbCrwgfzPncrJPSFVGPnrcJSVznmV",
                                      "bLpvwQwMwpjWMgfvgZTsDsBttqHRjTqHlH",
                                      "mpmGpCpmlpmwfmCQVppCVfQSSjvSqgWvvvDgNwWDgnnDnW",
                                      "RBLsHRJBRrHJWFDWSNqFWj",
                                      "zZBLdsdcZrsBjGfpGVpTTPGlVc",
                                      "NBbTzgwSNmrFWpVrzrFM",
                                      "LnZQtQlZVnMrFBBG",
                                      "CCdtddBtPdNqcvHSCCcg",
                                      "ZFbZPHbZPTQVVlsGNF",
                                      "qtvDWvgRftqGNccCNVThDs",
                                      "fRwGBBjBppdMdBMZ",
                                      "GffflsZsPZVfjsssNfZsJNNZVcMDSqMWFcwFMMpcTMTTFSTS",
                                      "LhrCmvzcRbbhtmRdTCMDwWMpDWqqqMpW",
                                      "dvRQmBBvLzBRRvRhhcdbhdRgjHQNllJsfsNlZZljZGGNQN",
                                      "wjbMPsbfLzVCTMVbjLplmpshhSpHShhJhtsm",
                                      "ZrcqZTDTGDqFdJtGmdGSpl",
                                      "QNNrWvQRqRNWnTQRvqjPbjfWbCBCMbMLBwMV",
                                      "wRPRsppFfWJRlPRPFlpJfwSMzzZTBwBtZTTCMCMtdz",
                                      "vGLGrjcfrLVGjfnGTMCMtNNnCTnMtCBd",
                                      "VrjqhjhLVcrGVRqJmqQspmfFWm",
                                      "LRfdnmwMwdSBmfvJNrrgLhCNgqqJWs",
                                      "llctPPVTcPStgJgshCsrCs",
                                      "DpTlFpFVRFZRFFSv",
                                      "sPgRgsmdcqmgSvvFRRRRdqdFfTWZhhdZrZbbWfTpwDfbWTbw",
                                      "jLCCHtLljJzjlplfZSlwTfprZZ",
                                      "tBHVjQHzHQJBtSVmvRsvvFRqnGgv",
                                      "spppVDbVcbgVSFgFZZbGZgbJMRBTvHTvJJHGtHRwtMGvHT",
                                      "LldflzQLLQmQWQQfnwMWwHJtTtwRBcBt",
                                      "CPjfhCmNmNfFVchpchFVhp",
                                      "bZQJgQmQmTgnLBRtNPNnml",
                                      "ccszcqldGzhszrVsqdlHVNwLpppwHPHRtBBppDNRLt",
                                      "VSzVhVdcfrrhcqGrVhrssQQlMbJvFjMgbFSQggCvCv",
                                      "hHWVWhhlZDZVWNTgczWLjbtcTFFj",
                                      "JJnPnCdBCBnnRCjSsjStBgsbFttb",
                                      "MRpgCpGqdPRppJwpnRqRfZZhmvhHDrhllDHhhZGZ",
                                      "SPcgLDcLLnWFWCNVCRPT",
                                      "fhZQtsbtmbmfZTVTVRWfNvTCTT",
                                      "jhbbmzRsQzpLDcgLHLjg",
                                      "GSFRHrCCGRJDJtrgWdrL",
                                      "stcVQshQZBsBmjMsZhmMQQWDDvNWdncNWvzLgdDnzdDN",
                                      "sVwMBQBhVVjtQZVPlSfPCfwRpSCpRl",
                                      "bBHHJMJvBvWMJWqqccNNPhMCrclChQCC",
                                      "RPppPgfpwgmcQgrhmm",
                                      "tfwTwpFPGGwZSRtpVjJHbHLvSvLSqVLL",
                                      "jlJfZGjljJPBqJGnfGVMqGfrFWWddvDmFRDcmdFDdDvbDM",
                                      "hTCTsgsgwhTbvRdcFmsddpFd",
                                      "wbQNHTQLgCwSThhCgwnZnJfqnqJBlNlBnnVl",
                                      "CLlfbjjbLlbbDGbLzfCGhdtdWBthdBWsHvWHBnntWs",
                                      "rmJRJFqrDwVFTwFmSJvtvMtdJMMHBdBBndWt",
                                      "ZVrVVZpgTpZFSqmZqRNlNNfQQbpGjDQbbpPl",
                                      "mVCrhGHGmZhrNlDwbWnLWWvGLWWwnd",
                                      "PNsqgzspsgNFJNFfzqpWSWdwSvSPnvdWbSbvjd",
                                      "NzgJzqMcgscQqJcpJRzBmlrBRBDDlHZBBBHtHZ",
                                      "NJmNJDwcMmJNMbJJDNDqcGcsWRWHQzRPQjZLRGZWLQsjZQ",
                                      "dgSnTBgdpddtgShSTZjLRhRLHqWPPhPRPQ",
                                      "VgdTpBntlvBVrlfcbqJcMrfmcqmb",
                                      "wvqwvPwNJgFmLdvDJFDmDLvJlQZpMzSpBVflpdSSMlQnfldS",
                                      "WjCcRZCWRjjRtsZhRRhpSVBVnzplBfWnfBfSQz",
                                      "CbRbcsjHZrhbTRtsGbCrgNgDDPFFqvvJvJFDFw",
                                      "GlsCrbCChShqgqlbSCcVbqgVhBwjBDFBhBhdDWvwBFFvWvDv",
                                      "THmHMmtMnLfHRnzRZnfLBDWWsWzWFNsvWjjvjvFF",
                                      "mpHRtmZffHTTMpmLMLLnJtJCgScScsPlblcpCrPbblCPlq",
                                      "vscDLrcvrsLNStdTfBCvgJTqGBdd",
                                      "bwLbzRhbbdTfbgCB",
                                      "pplQzLwmPZVMStcDjFtQrS",
                                      "RMjCrhFJhRVRVCCFFsvmnvqrmbvqmqSmbrvm",
                                      "tzfpBgTHzttGzZpBfHGDBZHbccnGqbmvdNlGnSnlcvSwbn",
                                      "pDWTHDTzgTfWZpVVsWSPjRFSMsFs",
                                      "fmrfmrwVfjmrzjqCsqqvjsvvpG",
                                      "hFDVtFStVtJnPPtJNHbtQWGbQsCvCsQgpWGggdQC",
                                      "NBSDSNHStHNHnhStHNNrcflrmTzBlwmzrlMVVw",
                                      "SjtZZSdNcDldPQqndl",
                                      "BbgzgWgTmTBfwrbnDjQDwVPwDlnsVq",
                                      "zBBrCTTMBWLMWmfMfbbmrMtjNZLFJRRZSSvFFtStvGGJ",
                                      "CTCGLGCFRRSMGnZnLCTfdffhpbNbDfpdZBvhdv",
                                      "rJlqclVPHJWVrgPPQqjqgJlhBhDBBQdvbhwvNfhswfNpvb",
                                      "tltrcrHjlVWVCDzSGCCzLCGt",
                                      "sbHHsbCCHbLSVfJbbfSLNJBzvzMMPrhPPNztZlZNZhdt",
                                      "GTWjplTgDnGmQGpQnQhZrvvBMPztPzvrzvjZ",
                                      "mQgGWllcFcTFmgwcDppDQGTCqfsSLqsfSbqJqLSSFsbRfF",
                                      "jslsFjLLLLvFwWtQFTFDJQWp",
                                      "dGzdrNmRWqVBGcTbwpRDRnbJDRhT",
                                      "qzqzrrPNNrmfLPsjglHjgW",
                                      "QjCHcPfcgQSgPPcffQSmmmLmrJJpNpBMrJMtFrBBBMFrrpNS",
                                      "VGVZfDbbVVZWGvDbFrlBZNJBNlNMwwtM",
                                      "sbvfhqTGTRnhTVGvzgHmgQLQmPqzmPLm",
                                      "sLwnMHnbnLMjGpZsjGGtpc",
                                      "ggvJrNNTQgQrNvgqBqZCCjClWjGtWjCpGJFW",
                                      "TVdrqvVrTNTzBqQQzTRMfHbMwMbZMdMbHwRD",
                                      "bcfJQQJHsQPCpdpWdPbb",
                                      "RHjHDwZtrZmRDDtwtjRBVFdWVrrrBClldVphCF",
                                      "zDgwgNzjmDnMnzMMHncG",
                                      "vMHRvMhvHWRBRDHhRBwWvRBqLqbGwqnqnnNTbNqdNbbVVr",
                                      "pslgcZszJltrsZcZgNnnqbSSTSSndbNbzS",
                                      "cZcgsZgZZgPgmcpfJtfttWBQvmFWjDQDhBmFjDHvFr",
                                      "bVbBvdTTVLbCgCznLJsJcwHPczfz",
                                      "NFcDphSDrFjGtZNZjplZGZFnzPHPrzHHzJMnnwfPsPsRJs",
                                      "cGtGljFmWdvqmVCV",
                                      "qSNbTvcvTGTvGcgtBNvcbdrdjrnjRnjRVHdDqHrRHj",
                                      "ZZZZPLWPzPDCCsCRnRdwVFnjdwPVFP",
                                      "ChlCLLZftfcBvfDv",
                                      "cRtfctVgmRclmBFGbbMBDDFPtD",
                                      "svQZhHSHssjTvjpQjSSBBMJMJGDBpPbMzzpGzP",
                                      "ZsvsCTWhCHhSwwjrwbndldlRnfRNmb",
                                      "PQdTgdGpRcTccCfj",
                                      "hHFLHlHBhBlmlDFzHrhhfZNZbfNZcVWNVVZRDjCC",
                                      "LFLLMHJHSBhBFGGnMMvsGtGGtj",
                                      "fwmVnVCDVqpNQqqb",
                                      "ddBcZZWdvGWzBzsWvLvddlNHcHQPbQqqJQNNQHPHQT",
                                      "WgGvsMMzvgbntDhCmt",
                                      "JjwhFMmwjJwmCgTgSCSFlPLg",
                                      "WWbsbVtftBZWtnWtncbQvctTGLpLgCpzPPPlllpzlgPPTQ",
                                      "TBvnfBffWsfVtTvbZBTNjwjqddhMNqwRMMhdRMrq",
                                      "SllrbtTSQrSQrbrvvMvzFDsBsssWpWdWbGpGBWNWNW",
                                      "hhCfmmmjmPLCfmnPLfqPgqqNNBpjZBZQDNQdpWNpdBBsBp",
                                      "RhLfPhQLQfCRnHfqTHHrFJMrttTwTtzt",
                                      "BFrFBJMMJnnsNJBFCdLCnmvzbPdCmPnc",
                                      "LDLVHQRfDvdHdcCmcv",
                                      "llQDwqSVLwZLZSgsGZMNMgTjTMTr",
                                      "mrwdbqRhdCNGgZBHbH",
                                      "jVTPMjvjpvMfTfQfPlpHHZNnNBHgZDGsGMnCsZ",
                                      "TLlfQpffQvvzhtNqztRFtzcm",
                                      "DDfvJZZPDHVPSPcSvcgcWCsWQcTTdhQTTh",
                                      "dMwpbdjRtrFhhTsTFQWqhC",
                                      "bGRdNpbzlvLfDfZlLZ",
                                      "bdPQdcpdbpjFqpQcQwqqhhNRhJvWRfrrWBsJrfwN",
                                      "mMtlZfmtnLZtSnGDlmGWRRhrWLhJsBRvgRWghh",
                                      "DnMGCtmCzfGMbjdQbVzpqcFH",
                                      "jwnGggRBvvpBZCljCsCWrhhrsh",
                                      "FVMcFLqLMqcJfVtDqMJcHMHWCSblzzrWsdhSLlSzbrGCLz",
                                      "HQVFPDtDQDFFNTZpPgNnGgNn",
                                      "HNBHNqlqHJQBRNvdmZvmPdZZlpnT",
                                      "bDbbhDgSfzVVfnvPmfHmTZZd",
                                      "jgzbwrhVsDgsDWLwJqqBMqcqHL",
                                      "tzNtJzsJVBHzbjbglCHc",
                                      "nfmnGnmPhntCgHvtvmCj",
                                      "MStTwrMTWrTdBZSNLZJNVQ",
                                      "NVjmwmVGGwGFHstwFHMhTh",
                                      "psRSzzscZscZpgQQzqQtBBHTTlThHHtTTh",
                                      "rCprbpZccggcrRzbbRRbscvVVWWvNfvVWnGDCWVNddmd",
                                      "rphfGDgtPtllrPlFlGrhGjnmnTnjcBsncBBVpTTBmc",
                                      "SqqZMJCLwgCwJgQRqqgZQNwdBBsBBHVBdTHNsnVNBTccnc",
                                      "MJqZZMbqgzRCSJZwPtFfGzWhrrfGttWl",
                                      "cSZqqcwbqVzqCbqVqVZPsvvDCDrffngvphggndhdGh",
                                      "tTNTMWJNQJHMNGSSprfdGnfdth",
                                      "WNRHWWMJSRWzswbczsVPRs",
                                      "HCgcSMhSMBGMdvGf",
                                      "RNQqbDQqFdRFdmTZfGtPZvtGlQffll",
                                      "mNpdNrRDbTNrmbpzmpWmbpWcswhcHcjhscSHjSgVHwHn",
                                      "MwgcFgwMMcscCbMFsMFCgMgPPLWPvptvBvPvtvvWmBBzwG",
                                      "nhQQjTJRVDdQJrPpmnGGBmvtGvLz",
                                      "HdJQdJHjrJQDBQjhQVQJhdJcqlFHcSqsNbCbCqCHFqCFgC",
                                      "JvTnvWtdJLbhJHbMwwHjcGHCwHwQGQ",
                                      "mqtmsllmfqVFwMwMrrPjmQrC",
                                      "lfztRZSlRDRVzfdpWnSvWhNdbnpp",
                                      "rSvrgggzHTNzrHtnptpmlDngZjWj",
                                      "MdMhqMhsfMSRcGqRsQQRctjjdDnjtjClCjjpZnDlnt",
                                      "BBMRsQRfRcscGqBfRRsBssPBLLzNLFPwvVFFPTLbbLwHHTvS",
                                      "pCmCfdPFzmsFsDhFFDsttptpRtJjLnlJRtttHt",
                                      "ZQwgWZgqJhTTRtgV",
                                      "GNqWNvcqqQQrMMWcQzDDsSzBDBSssSmhhr"};

inline static int shift(char c)
{
    return islower(c) ? c - 'a' : c - 'A' + 26;
}

static uint64_t encode_to_bitfield(std::string_view s)
{
    uint64_t bf = 0;
    for (const auto c : s)
        bf |= (1llu << shift(c));
    return bf;
}

inline static int prio(uint64_t bf)
{
    for (int i = 1; i <= 64; ++i)
    {
        if (bf & 1) return i;
        bf >>= 1;
    }
}

int main()
{
    auto find_common = [](std::ranges::viewable_range auto &&r) {
        auto common = std::accumulate(r.begin(), r.end(), r[0], std::bit_and<uint64_t>());
        return prio(common);
    };
    auto const chunks =
        input | std::views::transform(encode_to_bitfield) | std::views::chunk(3);
    std::vector<int> group_prios(std::distance(cbegin(chunks), cend(chunks)));
    std::transform(chunks.begin(), chunks.end(), group_prios.begin(), find_common);
    std::cout << std::accumulate(group_prios.begin(), group_prios.end(), 0) << '\n';
    return 0;
}
